os: osx
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g ionic cordova
  - gem install bundler
  - bundle install
script:
  - ionic cordova build ios
